version: '3.9'

services:
  blog_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      SERPAPI_API_KEY: ${SERPAPI_API_KEY}
    volumes:
      - .:/app
    restart: unless-stopped
